# Generated by Django 3.2.11 on 2022-01-04 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
