# Generated by Django 3.2.11 on 2022-01-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_rename_comments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='color',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='avatar',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
